name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 0.1.0)'
        required: true
        default: '0.1.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Install ImageMagick
        run: sudo apt update && sudo apt-get install -y imagemagick
      
      - name: Make icon setup executable
        run: chmod +x setup_icon.sh

      - name: Make build script executable
        run: chmod +x build_packages.sh

      - name: Setup icons
        run: ./setup_icon.sh        
      
      - name: Build AppImage
        run: |
          VERSION=${{ steps.version.outputs.VERSION }} ./build_packages.sh appimage
      
      - name: Build Flatpak package
        run: |
          VERSION=${{ steps.version.outputs.VERSION }} ./build_packages.sh flatpak
      
      - name: List generated packages
        run: |
          echo "📦 Generated packages:"
          ls -lh dist/
      
      - name: Calculate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS
          cat SHA256SUMS
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multiwall-packages-${{ steps.version.outputs.VERSION }}
          path: |
            dist/*.AppImage
            dist/*.flatpak
            dist/SHA256SUMS
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.AppImage
            dist/*.flatpak
            dist/SHA256SUMS
          body: |
            # MultiWall v${{ steps.version.outputs.VERSION }}
            
            ## 📦 Installation
            
            ### AppImage (Universal Linux)
            ```bash
            chmod +x MultiWall-${{ steps.version.outputs.VERSION }}-x86_64.AppImage
            ./MultiWall-${{ steps.version.outputs.VERSION }}-x86_64.AppImage
            ```
            
            ### Flatpak (.flatpak)
            ```bash
            flatpak install --user ./MultiWall-${{ steps.version.outputs.VERSION }}-x86_64.flatpak
            flatpak run me.latinosoft.MultiWall
            ```
            
            ## 🔐 Verify checksums
            ```bash
            sha256sum -c SHA256SUMS
            ```
            
            ## 📝 Changelog
            See [CHANGELOG.md](CHANGELOG.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  test-packages:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version: ['22.04', '24.04']
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: multiwall-packages-${{ needs.build.outputs.version }}
      
      - name: Test Flatpak
        run: |
          # Instalar Flatpak
          sudo apt update
          sudo apt install -y flatpak
          
          # Agregar repositorio Flathub
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

          flatpak install --user -y --noninteractive flathub org.gnome.Platform//48 org.gnome.Sdk//48
          
          # Encontrar el archivo .flatpak
          FLATPAK_FILE=$(ls MultiWall-*.flatpak 2>/dev/null | head -n 1)
          
          if [ -z "$FLATPAK_FILE" ]; then
            echo "❌ No se encontró archivo .flatpak"
            ls -la
            exit 1
          fi
          
          echo "📦 Instalando: $FLATPAK_FILE"
          
          # Instalar el Flatpak
          flatpak install --user -y "$FLATPAK_FILE"
          
          # Verificar instalación
          if flatpak info me.latinosoft.MultiWall &> /dev/null; then
            echo "✅ Aplicación MultiWall (Flatpak) está instalada"
            flatpak info me.latinosoft.MultiWall
          else
            echo "❌ Aplicación MultiWall (Flatpak) no encontrada"
            exit 1
          fi
      
      - name: Test AppImage
        run: |
          sudo apt update
          sudo apt install -y file
          
          # Encontrar el archivo AppImage
          APPIMAGE_FILE=$(ls MultiWall-*.AppImage 2>/dev/null | head -n 1)
          
          if [ -z "$APPIMAGE_FILE" ]; then
            echo "❌ No se encontró archivo .AppImage"
            ls -la
            exit 1
          fi
          
          echo "📦 Verificando: $APPIMAGE_FILE"
          
          # Hacer ejecutable
          chmod +x "$APPIMAGE_FILE"
          
          # Verificar tipo de archivo
          FILE_TYPE=$(file "$APPIMAGE_FILE")
          echo "Tipo: $FILE_TYPE"
          
          if echo "$FILE_TYPE" | grep -q "ELF.*executable"; then
            echo "✅ AppImage es válido"
            ls -lh "$APPIMAGE_FILE"
          else
            echo "❌ AppImage no es un ejecutable válido"
            exit 1
          fi